language: php
addons:
  postgresql: "9.4"
services:
  - postgresql
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=mysql
    - php: 5.6
      env: DB=mysql BEHAT=true
    - php: 5.6
      env: DB=pgsql
    - php: 5.6
      env: DB=pgsql BEHAT=true
    - php: 5.5
      env: DB=sqlite
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - cd ..
  - git clone https://github.com/neos/flow-development-distribution.git
  - cd flow-development-distribution
install:
  - composer install --no-progress --no-interaction
  - rm -rf Packages/Framework
  - mv ../flow-development-collection Packages/Framework
before_script:
  - if ([ "$BEHAT" == "true" ] || [ "$DB" == "sqlite" ]); then phpenv config-rm xdebug.ini; fi
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - rm Configuration/Routes.yaml
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - if [ "$BEHAT" = "true" ]; then composer install -d Build/Behat; fi
script:
  - if [ "$BEHAT" != "true" ]; then bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml; fi
  - if [ "$BEHAT" != "true" ]; then bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --testsuite "Framework tests"; fi
  - if [ "$BEHAT" = "true" ]; then FLOW_CONTEXT=Testing/Behat ./flow doctrine:create; fi
  - if [ "$BEHAT" = "true" ]; then bin/behat --ansi --stop-on-failure -f progress -c Packages/Framework/TYPO3.Flow/Tests/Behavior/behat.yml.dist; fi
notifications:
  email: false
  slack:
    rooms:
      secure: Ya3VRC3SSmPBDnQEADUimct2SkCEymMZTo3Zmkv7OoadmSl9vWOGd0HIDJjOShUtNbLWPkYeiNxIyOegHXYhFoVL2lX9sp2MLVdv9JK/rKQITHrESl+AulqYkq1bQiPzTfltludljUZmhZUxt1jpqazqp5iCGzWvKYawDjIaretLFvs3jsG6ZGnnFiN88HF4d5K+vImslckzCwh3pcQk227uaug/dXVJySx9/9VsCjhNTq2avcVziz/4vswuR/XSa6iPJ/j+7YBzsvVUOybKPQLtG6tx5THk38JkOjg+P09Mrz+Sz18aAROzrITV/gvjk1D+fA1wy/16mEmkfYmRVogi7DRCUGK5gd9wmQWRuYrTsMubQGJp1eSu/IBe3Z8eStRQUAK65DykwCAAyIhtLfOqH6mNy++dH5icYeSdXnw0TC0eIE0xcuWpNCansQN3ZQ1/wjXgH42LNc9WXs+D+2+Kns8Fm9HCwroVG6ws5tRB9+bbYpReIiL0b5N/p2kpiKeHR9Xn5vkdBzUGaM/O/pZIqvPmAUvIenfLqQ3k+oHvQyRZBzPTexi+93PEOd+jk3kC7vCvi9zsDxzGjbxC190T95zxZ/i6k7rcWImcC7HCAEW6aWqgARa03pJsrKvZD8IRTOVu8B17TSI4SkbjdjZi1Wvs3N68pBPX+2EaQ9M=
    on_success: change
    on_failure: change
    on_start: never
    on_pull_requests: false
