language: php
php:
  - 5.5
  - 5.6
#  - 7.0
env:
  - DB=sqlite
  - DB=mysql
#  - DB=pgsql
before_install:
  - cd ..
  - git clone https://github.com/neos/flow-base-distribution.git
  - cd flow-base-distribution
install:
  - composer require "neos/flow-development-collection dev-master"
  - rm -rf Packages/Framework
  - mv ../flow-development-collection Packages/Framework
before_script:
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - rm Configuration/Routes.yaml
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - FLOW_CONTEXT=Testing ./flow configuration:show --type Settings --path TYPO3.Flow.persistence.backendOptions
script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml
  - bin/phpunit --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml
