language: php
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=mysql
#    - php: 5.6
#      env: DB=pgsql
    - php: 5.5
      env: DB=sqlite
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - cd ..
  - git clone https://github.com/neos/flow-development-distribution.git -b 2.3
  - cd flow-development-distribution
install:
  - composer install
  - rm -rf Packages/Framework
  - mv ../flow-development-collection Packages/Framework
before_script:
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - rm Configuration/Routes.yaml
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
script:
  - bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --testsuite "Framework tests"
