language: php
matrix:
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=mysql
#    - php: 5.6
#      env: DB=pgsql
    - php: 5.5
      env: DB=sqlite
before_install:
  - cd ..
  - git clone https://github.com/neos/flow-base-distribution.git -b 3.0
  - cd flow-base-distribution
install:
  - composer require "neos/flow-development-collection 3.0.x-dev"
  - rm -rf Packages/Framework
  - mv ../flow-development-collection Packages/Framework
before_script:
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - rm Configuration/Routes.yaml
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - FLOW_CONTEXT=Testing ./flow configuration:show --type Settings --path TYPO3.Flow.persistence.backendOptions
script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml
  - bin/phpunit --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --testsuite "Framework tests"
