files:
  -
    source: 'TYPO3.Flow/Resources/Private/Translations/en/**/*.xlf'
    translation: 'TYPO3.Flow/Resources/Private/Translations/%locale_with_underscore%/**/%original_file_name%'
    update_option: 'update_as_unapproved'
    languages_mapping:
      locale_with_underscore:
        'af': 'af'
        'ar': 'ar'
        'ca': 'ca'
        'cs': 'cs'
        'da': 'da'
        'de': 'de'
        'el': 'el'
        'en': 'en'
        'es': 'es'
        'fi': 'fi'
        'fr': 'fr'
        'he': 'he'
        'hi': 'hi'
        'hu': 'hu'
        'id-ID': 'id_ID'
        'it': 'it'
        'ja': 'ja'
        'kk-KZ': 'kk_KZ'
        'km': 'km'
        'ko': 'ko'
        'la-LA': 'la'
        'lv': 'lv'
        'mr': 'mr'
        'nl': 'nl'
        'no': 'no'
        'pl': 'pl'
        'pt-PT': 'pt'
        'pt-BR': 'pt_BR'
        'ro': 'ro'
        'ru': 'ru'
        'sr': 'sr'
        'sv-SE': 'sv'
        'tr': 'tr'
        'uk': 'uk'
        'vi': 'vi'
        'zh-CN': 'zh'
        'zh-TW': 'zh_TW'
  -
    source: 'TYPO3.Fluid/Resources/Private/Translations/en/**/*.xlf'
    translation: 'TYPO3.Fluid/Resources/Private/Translations/%locale_with_underscore%/**/%original_file_name%'
    update_option: 'update_as_unapproved'
    languages_mapping:
      locale_with_underscore:
        'af': 'af'
        'ar': 'ar'
        'ca': 'ca'
        'cs': 'cs'
        'da': 'da'
        'de': 'de'
        'el': 'el'
        'en': 'en'
        'es': 'es'
        'fi': 'fi'
        'fr': 'fr'
        'he': 'he'
        'hi': 'hi'
        'hu': 'hu'
        'id-ID': 'id_ID'
        'it': 'it'
        'ja': 'ja'
        'kk-KZ': 'kk_KZ'
        'km': 'km'
        'ko': 'ko'
        'la-LA': 'la'
        'lv': 'lv'
        'mr': 'mr'
        'nl': 'nl'
        'no': 'no'
        'pl': 'pl'
        'pt-PT': 'pt'
        'pt-BR': 'pt_BR'
        'ps-AF': 'ps'
        'ro': 'ro'
        'ru': 'ru'
        'sr': 'sr'
        'sv-SE': 'sv'
        'tr': 'tr'
        'uk': 'uk'
        'vi': 'vi'
        'zh-CN': 'zh'
        'zh-TW': 'zh_TW'
